package com.mockup.core

/**
 * Describes a generated provider that cannot be reached through `Mockup.get<T>()` because the
 * requested Kotlin type is erased to a raw JVM class at runtime.
 *
 * @property rawClassName Fully qualified JVM/Kotlin class name visible at runtime.
 * @property targetTypeName Concrete source type generated by the processor.
 * @property providerClassName Fully qualified generated provider class name.
 * @property accessorName Generated `Mockup` extension property name.
 * @property accessorImport Fully qualified import for [accessorName].
 * @since 2.0.0
 */
internal data class MockupProviderHint constructor(
    val rawClassName: String,
    val targetTypeName: String,
    val providerClassName: String,
    val accessorName: String,
    val accessorImport: String,
)
